name: Run on Specific Branch Pattern

on:
  push:
    branches:
      - 'feature/*'  # Matches any branch starting with "feature/"
      - 'release/**' # Matches any branch inside "release/"
      - 'Version-[0-9]+.[0-9]+' # Matches branches like "Version-1.0", "Version-2.3"

jobs:
  log_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Commit Details
        run: |
          echo "Commit made to branch: ${{ github.ref }}"
          echo "Commit ID: ${{ github.sha }}"
          echo "Commit Message: $(git log -1 --pretty=%B)"
