name: Multi-Step Sequential Workflow

on:
  push:
    branches:
      - main  # Runs only on the main branch (change as needed)

jobs:
  sequential_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout Repository
        uses: actions/checkout@v4

      - name: Step 2 - Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Step 3 - Install Dependencies
        run: sleep 10

      - name: Step 4 - Run Tests
        run: sleep 10

      - name: Step 5 - Build Project
        run: sleep 15

      - name: Step 6 - Deploy Application (Only if All Previous Steps Succeed)
        run: echo "Deploying application..."
